---
language: ruby
cache: bundler
before_install: gem install bundler
rvm:
  - 3.0.0
  - 2.7.2
  - 2.6.6
  - 2.5.8
gemfile:
  - gemfiles/Gemfile.rails_6.1
  - gemfiles/Gemfile.rails_6.0
  - gemfiles/Gemfile.rails_5.2
jobs:
  exclude:
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails_5.2
